version: '3.8'

services:
  postgres_kibe:
    image: postgres:latest
    container_name: postgres_kibe
    env_file: .env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_kibe
    env_file: .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres_kibe
      - redis
    volumes:
      - .:/usr/src/app
    command: npm start

  redis:
    image: redis:latest
    container_name: redis_kibe
    env_file: .env.docker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
